apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  source:
    path: jenkins
    repoURL: https://github.com/argoproj/argoproj-deployments
    targetRevision: HEAD
    helm:
      version: v2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  project: default
  ignoreDifferences:
  - group: ''
    jsonPointers:
    - /data/jenkins-admin-password
    kind: Secret
