---
kind: Namespace
apiVersion: v1
metadata:
  name: dns-test
  annotations:
    linkerd.io/inject: enabled

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: dns-test
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: nginx

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: dns-test
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/hostname: sandbox.securingsam.io
spec:
  rules:
  - host: ttttt.sandbox.securingsam.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx
              port:
                number: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dns-test
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http
